language: generic
sudo: required

matrix:
  include:
   - env: VERSION=7.10.3
     os: linux

before_install: true
install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install --force-yes ghc-$VERSION-prof ghc-$VERSION-dyn
  - export PATH="/opt/ghc/$VERSION/bin:$PATH"
before_script: true
script:
 - ghc --version
 - echo "main = return ()" > Main.hs
 - ghc --make Main.hs
 - ghc --make Main.hs -prof
